---
title: "Locations_crosstalk"
author: "Emma Mendelsohn"
date: "9/21/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = TRUE, message=FALSE)

library(crosstalk)
library(leaflet)
library(DT)
library(tidyverse)
library(here)

locs <- read_csv(here("scripts", "locations", "location_coords.csv"))
```

STUDY LOCATIONS
```{r}
# Wrap data frame in SharedData
sl_locs <- locs %>%
  select(study_location_lat, study_location_lon, study_location, study_id) %>%
  rename(latitude = study_location_lat, longitude = study_location_lon) %>%
  filter(!is.na(latitude)) %>%
  unique() #some dups for travel locs

sd <- SharedData$new(sl_locs)

# Use SharedData like a dataframe with Crosstalk-enabled widgets
bscols(
  leaflet(sd) %>% addTiles() %>% addMarkers(),
  datatable(sd, extensions="Scroller", style="bootstrap", class="compact", width="100%",
            options=list(deferRender=TRUE, scrollY=300, scroller=TRUE))
)
```
TRAVEL LOCATIONS
```{r}
# Wrap data frame in SharedData
sl_locs <- locs %>%
  select(travel_location_lat, travel_location_lon, travel_location, study_id) %>%
  rename(latitude = travel_location_lat, longitude = travel_location_lon) %>%
  filter(!is.na(latitude)) 

sd <- SharedData$new(sl_locs)

# Use SharedData like a dataframe with Crosstalk-enabled widgets
bscols(
  leaflet(sd) %>% addTiles() %>% addMarkers(),
  datatable(sd, extensions="Scroller", style="bootstrap", class="compact", width="100%",
            options=list(deferRender=TRUE, scrollY=300, scroller=TRUE))
)

```
RESIDENCE LOCATIONS
```{r}
# Wrap data frame in SharedData
sl_locs <- locs %>%
  select(residence_location_lat, residence_location_lon, residence_location, study_id) %>%
  rename(latitude = residence_location_lat, longitude = residence_location_lon) %>%
  filter(!is.na(latitude)) %>%
  unique() #some dups for travel locs

sd <- SharedData$new(sl_locs)

# Use SharedData like a dataframe with Crosstalk-enabled widgets
bscols(
  leaflet(sd) %>% addTiles() %>% addMarkers(),
  datatable(sd, extensions="Scroller", style="bootstrap", class="compact", width="100%",
            options=list(deferRender=TRUE, scrollY=300, scroller=TRUE))
)

```

